#!/usr/bin/env bash

# Shared Hydra overrides for both v2 curriculum stages.
V2_REWARD_OVERRIDES=(
  '++manager_env.rewards._target_=sonic_debug.phase_rewards.V2RewardsCfg'

  '++manager_env.rewards.support_contact._target_=isaaclab.managers.RewardTermCfg'
  '++manager_env.rewards.support_contact.func=sonic_debug.phase_rewards:phase_support_contact'
  '++manager_env.rewards.support_contact.weight=0.5'
  '++manager_env.rewards.support_contact.params.command_name=motion'
  '++manager_env.rewards.support_contact.params.start_frame=0'
  '++manager_env.rewards.support_contact.params.end_frame=24'
  '++manager_env.rewards.support_contact.params.wrist_body_names=[left_wrist_yaw_link,right_wrist_yaw_link]'
  '++manager_env.rewards.support_contact.params.ankle_body_names=[left_ankle_roll_link,right_ankle_roll_link]'
  '++manager_env.rewards.support_contact.params.min_force=20.0'

  '++manager_env.rewards.takeoff_contact._target_=isaaclab.managers.RewardTermCfg'
  '++manager_env.rewards.takeoff_contact.func=sonic_debug.phase_rewards:phase_support_contact'
  '++manager_env.rewards.takeoff_contact.weight=0.5'
  '++manager_env.rewards.takeoff_contact.params.command_name=motion'
  '++manager_env.rewards.takeoff_contact.params.start_frame=25'
  '++manager_env.rewards.takeoff_contact.params.end_frame=40'
  '++manager_env.rewards.takeoff_contact.params.wrist_body_names=[left_wrist_yaw_link,right_wrist_yaw_link]'
  '++manager_env.rewards.takeoff_contact.params.ankle_body_names=[left_ankle_roll_link,right_ankle_roll_link]'
  '++manager_env.rewards.takeoff_contact.params.min_force=20.0'

  '++manager_env.rewards.takeoff_pelvis_vertical_velocity._target_=isaaclab.managers.RewardTermCfg'
  '++manager_env.rewards.takeoff_pelvis_vertical_velocity.func=sonic_debug.phase_rewards:phase_pelvis_vertical_velocity_tracking'
  '++manager_env.rewards.takeoff_pelvis_vertical_velocity.weight=2.0'
  '++manager_env.rewards.takeoff_pelvis_vertical_velocity.params.command_name=motion'
  '++manager_env.rewards.takeoff_pelvis_vertical_velocity.params.start_frame=25'
  '++manager_env.rewards.takeoff_pelvis_vertical_velocity.params.end_frame=40'
  '++manager_env.rewards.takeoff_pelvis_vertical_velocity.params.std=0.35'

  '++manager_env.rewards.airborne_right_leg_position._target_=isaaclab.managers.RewardTermCfg'
  '++manager_env.rewards.airborne_right_leg_position.func=sonic_debug.phase_rewards:phase_relative_body_position_tracking'
  '++manager_env.rewards.airborne_right_leg_position.weight=2.0'
  '++manager_env.rewards.airborne_right_leg_position.params.command_name=motion'
  '++manager_env.rewards.airborne_right_leg_position.params.start_frame=41'
  '++manager_env.rewards.airborne_right_leg_position.params.end_frame=69'
  '++manager_env.rewards.airborne_right_leg_position.params.std=0.18'
  '++manager_env.rewards.airborne_right_leg_position.params.body_names=[right_hip_roll_link,right_knee_link,right_ankle_roll_link]'

  '++manager_env.rewards.airborne_right_leg_orientation._target_=isaaclab.managers.RewardTermCfg'
  '++manager_env.rewards.airborne_right_leg_orientation.func=sonic_debug.phase_rewards:phase_relative_body_orientation_tracking'
  '++manager_env.rewards.airborne_right_leg_orientation.weight=1.0'
  '++manager_env.rewards.airborne_right_leg_orientation.params.command_name=motion'
  '++manager_env.rewards.airborne_right_leg_orientation.params.start_frame=41'
  '++manager_env.rewards.airborne_right_leg_orientation.params.end_frame=69'
  '++manager_env.rewards.airborne_right_leg_orientation.params.std=0.3'
  '++manager_env.rewards.airborne_right_leg_orientation.params.body_names=[right_hip_roll_link,right_knee_link,right_ankle_roll_link]'

  '++manager_env.rewards.airborne_right_leg_joint_pose._target_=isaaclab.managers.RewardTermCfg'
  '++manager_env.rewards.airborne_right_leg_joint_pose.func=sonic_debug.phase_rewards:phase_joint_position_tracking'
  '++manager_env.rewards.airborne_right_leg_joint_pose.weight=1.0'
  '++manager_env.rewards.airborne_right_leg_joint_pose.params.command_name=motion'
  '++manager_env.rewards.airborne_right_leg_joint_pose.params.start_frame=41'
  '++manager_env.rewards.airborne_right_leg_joint_pose.params.end_frame=69'
  '++manager_env.rewards.airborne_right_leg_joint_pose.params.std=0.25'
  '++manager_env.rewards.airborne_right_leg_joint_pose.params.joint_names=[right_hip_pitch_joint,right_hip_roll_joint,right_hip_yaw_joint,right_knee_joint,right_ankle_pitch_joint,right_ankle_roll_joint]'

  '++manager_env.rewards.airborne_pelvis_orientation._target_=isaaclab.managers.RewardTermCfg'
  '++manager_env.rewards.airborne_pelvis_orientation.func=sonic_debug.phase_rewards:phase_anchor_orientation_tracking'
  '++manager_env.rewards.airborne_pelvis_orientation.weight=1.0'
  '++manager_env.rewards.airborne_pelvis_orientation.params.command_name=motion'
  '++manager_env.rewards.airborne_pelvis_orientation.params.start_frame=41'
  '++manager_env.rewards.airborne_pelvis_orientation.params.end_frame=69'
  '++manager_env.rewards.airborne_pelvis_orientation.params.std=0.3'

  '++manager_env.rewards.landing_pelvis_tracking._target_=isaaclab.managers.RewardTermCfg'
  '++manager_env.rewards.landing_pelvis_tracking.func=sonic_debug.phase_rewards:phase_anchor_position_tracking'
  '++manager_env.rewards.landing_pelvis_tracking.weight=0.5'
  '++manager_env.rewards.landing_pelvis_tracking.params.command_name=motion'
  '++manager_env.rewards.landing_pelvis_tracking.params.start_frame=70'
  '++manager_env.rewards.landing_pelvis_tracking.params.end_frame=80'
  '++manager_env.rewards.landing_pelvis_tracking.params.std=0.25'
)
